[package]
name = "chords-quiz"
version = "0.0.1"
authors = ["Lesha Koss <lesha.kostiuchenko@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7.3"
midir = "0.7.0"
wmidi = "3.1.0"
colored = "1.9"
dialoguer = "0.7.1"
